var:
  pipelineName: devnext_workshop_203
  gitRepoResource: devnext_sample
  gitProvider: testproject
  path: ganavikumar/pipelines-devnext
  branches: main
  artifactory: hk_artifactory_1
  dockerRepoName: cpe-docker-local-devnext
  jfrogPlatformInstance: devnextsaas1.jfrog.io